### ISSUE TITLE
Data about factors regulating genes in multiple biological processes

### ISSUE THREAD

**Issue by llrs** [dledezma/functional_homogeneity#1]
I found in the [preprint](https://www.biorxiv.org/content/biorxiv/early/2018/11/28/479857.full.pdf) that "All regulon datasets, random regulons, GENSOR Units, custom scripts and the raw data used in this study are available at GitHub". However I only see a License. Are these datasets now on https://github.com/dledezma/gensor_units ?

**Comment by dledezma** [comment]
The preprint is accurate. We are having technical difficulties and all data will be available tomorrow at the latest. Our sincere apologies.

https://github.com/dledezma/gensor_units includes all the data from this paper: 
https://www.frontiersin.org/articles/10.3389/fmicb.2017.01466/full

**Comment by llrs** [comment]
Great! Thanks ! Looking forward to the revised paper and the data. :smiley:

**Comment by dledezma** [comment]
All set :). We will keep adding documentation on the GENSOR Unit format (5 txt files), in case someone wants to perform independent analysis on the data. At this point, it should be enough to replicate preprint results.

Let me know if you need further information on any analysis through here or at dledezma@lcg.unam.mx

**Comment by llrs** [comment]
Great! Thanks, I will read it with great interest!
